id: I97614E40
default_language: sa
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-10 00:25:53.502494
last_modified: 2023-02-10 00:25:53.502622
source_metadata:
  title: 'Asaṅga: Triśatikāyāḥ Prajñāpāramitāyāḥ Kārikāsaptatiḥ'
  language: sa
bases:
  '5848':
    base_file: 5848.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
